### ISSUE TITLE
Create basic neural network code

### ISSUE THREAD

**Issue by williamjameshandley** [DarkMachines/pyBAMBI#10]
Leading on from #3, PR #9 introduced a simple 'nearest neighbor' neural network to act as a template for better implementations. Any volunteers with experience implementing neural networks would be much appreciated.

**Comment by mjw63** [comment]
I'm happy to take on implementing keras-based neural nets, and I should be able to make progress by the December 21st meeting.

**Comment by mjw63** [comment]
Ahead of the meeting next week, I have now added a keras-based neural network interpolation, plus an associated test which takes random Gaussian data, interpolates it, and checks the interpolated value for a couple of the original parameter points.

**Comment by williamjameshandley** [comment]
A great start. We should get #12 passing the tests, merge into master and then add a new issue so that other people can weigh in on how to make the NN choice more general.
