### ISSUE TITLE
Test suite should include MPI and OSX

### ISSUE THREAD

**Issue by williamjameshandley** [DarkMachines/pyBAMBI#2]
To do this, we need to to update the .travis.yml file, making sure that mpi libraries are installed (both on system, and in mpi4py).

This should be done as a build matrix, i.e. for compiling with and without MPI using [environment variables](https://docs.travis-ci.com/user/environment-variables/)

**Comment by mamuzic** [comment]
I tried to run the python -m pytest tests, but the modules pypolychord and pymultinest seem to be missing. Should these be added?
Cheers,
Judita

**Comment by williamjameshandley** [comment]
You need to install pypolychord and pymultinest separately unfortunately (as they're not currently pip-installable). 

* https://github.com/DarkMachines/pyBAMBI/wiki/MultiNest-installation
* https://github.com/DarkMachines/pyBAMBI/wiki/PolyChord-installation

If anybody has a way of automating this, please let me know

**Comment by mamuzic** [comment]
Thanks! Will try this.
Cheers,
Judita
