### ISSUE TITLE
Implement BAMBI framework in python

### ISSUE THREAD

**Issue by williamjameshandley** [DarkMachines/pyBAMBI#4]
This will require carefully reading section 3.3.0 and 3.4 of the [BAMBI paper](https://arxiv.org/abs/1110.2997) (skip 3.3.1 and 3.3.2, as they are skynet-specific). Requires a placeholder function to be delivered from #3

**Comment by williamjameshandley** [comment]
From minutes of meeting @mjw63 

We need to think about 
* the persistence of the keras model 
   * should it be a global object? 
   * Should the  dumper function be moved to its own class?
* whether to train it from scratch with randomised initial weights/biases, or start from the previous values (BAMBI did the latter). 

@rruizdeaustri and @joaquinvanschoren will work on this in January with @williamjameshandley , with the aim of getting some basic progress by the start of February when @mjw63  (plus @patscott) will be in Cambridge for coding.

**Comment by williamjameshandley** [comment]
@ndsim has also expressed an interest in this issue alongside @rruizdeaustri and @joaquinvanschoren

**Comment by joaquinvanschoren** [comment]
How did BAMBI do the initialization? Where the previous values from very related tasks?

**Comment by williamjameshandley** [comment]
For the first training, [SkyNet](https://arxiv.org/abs/1309.0790) will have used a 'pre-training' scheme. It's likely that things have moved on since 2006 in this regard, and tensorflow includes this by default. 

For subsequent re-trainings, as the live points move up the distribution, the previously successful weights are used for initialisation, with the intuition here that these should be similar (not obviously true, and something we should test as we switch to modern networks).
